apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: {{ .Values.namespace.name }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9115'
spec:
  selector: 
    app: blackbox
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.blackboxPort }}
      targetPort: 9115
      protocol: TCP
