apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      initContainers:
      - name: gitclone
        image: alpine/git
        command: ['git', 'clone', '-b', 'homolog', 'https://github.com/viniciusfelix1/eks_cluster.git']
        securityContext:
          runAsUser: 0
          capabilities:
            drop:
            - ALL
        volumeMounts:
          - mountPath: /git
            name: grafana-dash
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        securityContext:
          runAsUser: 0
          capabilities:
            drop:
            - ALL
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /var/lib/grafana/dashboards
            name: grafana-dash
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-dashboards
            readOnly: false
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: "grafana-storage"
        - name: grafana-dash
          persistentVolumeClaim:
            claimName: "grafana-dash"
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-dashboards
          configMap:
              defaultMode: 420
              name: grafana-dashboards
