apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "sc-grafana"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ .Values.sc.type }}
  fsType: {{ .Values.sc.fsType}}
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - {{ .Values.sc.az }}
