apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: {{ .Values.namespace.name }}
  labels:
    app: prometheus-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.image.repository }}
          args:
            {{ range .Values.container.args }}
              - {{ . }}
            {{ end }}
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheusconfig
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheusconfig
          configMap:
            defaultMode: 420
            name: prometheuscm
  
        - name: prometheus-storage-volume
          emptyDir: {}
