apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace.name }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9090'
spec:
  selector: 
    app: prometheus
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090 
      protocol: TCP
