apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - mountPath: "/var/www/html/images"
          name: mediawiki-img
      #  - mountPath: "/var/www/html/session"
      #    name: mediawiki-session
        - mountPath: "/usr/local/etc/php"
          name: config-php
      volumes:
       - name: mediawiki-img
         persistentVolumeClaim:
           claimName: "pvc-images"
       #- name: mediawiki-session
       #  persistentVolumeClaim:
       #    claimName: "pvc-session"
       - name: config-php
         configMap:
           name: {{ .Chart.Name }} 
