apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  clusterIP: None
  ports:
    - port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    app: memcached
