apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Chart.Name }}
  resources:
    requests:
      storage: 1Gi
