apiVersion: v1
kind: Secret
metadata:
  name: wiki-db
data:
  MEDIAWIKI_SITE: {{ .Values.site }}
  MEDIAWIKI_URL: {{ .Values.url }}
  MYSQL_HOST: {{ .Values.dbConn.host }}
  MYSQL_NAME: {{ .Values.dbConn.name }}
  MYSQL_USER: {{ .Values.dbConn.user }}
  MYSQL_PW: {{ .Values.dbConn.pw }}
