apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "pvc-grafana"
  namespace: {{ .Values.namespace.name }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "sc-grafana"
  resources:
    requests:
      storage: 1Gi

