apiVersion: v2
name: mediawiki
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - name: Vinícius Felix
    email: vinicius.felix.1@hotmail.com
    url: https://www.linkedin.com/in/viniciusfelix1/
