# Default values for mediawiki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: viniciusfelix1/mediawiki
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Variaveis para o StorageClass
sc:
  type: gp2
  fsType: ext4

# Informações sobre o site
mediawiki_site: 'Vinicius Mediawiki'
mediawiki_url: 'wiki.vinicius.io'

# Variaveis para conexão mediawiki x db
# A Senha para o banco pode ser passada em base64. Para isso rode "echo -n "SENHA" | base64"
dbConn:
  host: 'mediawikirds.czg7vysvgykx.us-east-1.rds.amazonaws.com'
  name: 'mediawikirds'
  user: 'mediawiki'
  pw: 'NmFad3RVV3R2UjQ='

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
