# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  name: monitoring

replicaCount: 1

image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

container:
 args: 
   - --config.file=/etc/prometheus/prometheus.yml
   - --storage.tsdb.path=/prometheus/
sc:
  type: gp2
  fsType: ext4
  az: us-east-1a

service:
  type: ClusterIP
  port: 80
  grafanaPort: 3000
  blackboxPort: 9115

blackbox:
  targets:
    - http://mediawiki.default.svc/index.php/Main_Page
    - http://api.default.svc
